#' Get Path for slideimp Data
#'
#' Retrieves the path to the slideimp data directory.
#'
#' @details
#' The path is determined by:
#' \enumerate{
#'   \item Environment variable `SLIDEIMP` (if set)
#'   \item Base R default via `tools::R_user_dir("slideimp", "data")`
#' }
#'
#' To override permanently, add to your `~/.Renviron` (i.e., `file.edit("~/.Renviron")`):
#' \preformatted{
#' SLIDEIMP="/your/custom/path"
#' }
#'
#' To override temporarily, use [set_slideimp_path()].
#'
#' @param create Logical. If `TRUE`, creates the directory if it doesn't exist
#'   and checks writability. Default is `FALSE`.
#'
#' @return A character string with the normalized path.
#' @export
#'
#' @examples
#' get_slideimp_path()
#'
get_slideimp_path <- function(create = FALSE) {
  stopifnot(is.logical(create), length(create) == 1L)

  path <- Sys.getenv("SLIDEIMP", unset = "")

  if (!nzchar(path)) {
    path <- tools::R_user_dir("slideimp", which = "data")
  }

  path <- fs::path_norm(fs::path_expand(path))

  if (create) {
    if (!fs::dir_exists(path)) {
      fs::dir_create(path, recurse = TRUE)
    }
    if (!fs::file_access(path, "write")) {
      stop("Directory is not writable: ", path, call. = FALSE)
    }
  }

  return(path)
}

#' Set Path for slideimp Data
#'
#' Sets the slideimp data directory path for the current R session.
#'
#' @param path Character string specifying the directory path, or `NULL` to
#'   reset to default.
#'
#' @return Invisibly returns `NULL`.
#' @export
#'
#' @examples
#' # default path
#' get_slideimp_path()
#'
#' # set path for this session
#' set_slideimp_path("test")
#' get_slideimp_path()
#'
#' # reset to default
#' set_slideimp_path(NULL)
#' get_slideimp_path()
set_slideimp_path <- function(path) {
  checkmate::assert_string(path, null.ok = TRUE)

  if (is.null(path)) {
    Sys.unsetenv("SLIDEIMP")
  } else {
    Sys.setenv(SLIDEIMP = path)
  }

  invisible(NULL)
}

#' Dependency Factory
#'
#' This function factory generate functions to load in these data based on a
#' template.
#'
#' @param object_name name of object
#' @param object_hash hash of object
#'
#' @keywords internal
load_data_function <- function(object_name, object_hash) {
  function(path = NULL, ...) {
    full_object_name <- paste0(force(object_name), ".fst")
    # input validation
    checkmate::assert_character(path, len = 1, null.ok = TRUE)
    file_path <- if (!is.null(path)) {
      stopifnot("Provided file/dir doesn't exists" = dir.exists(path) || file.exists(path))
      info <- file.info(path)
      # if pass a folder
      if (info$isdir) {
        # then convert path to read into folder/file.fst
        file.path(path, full_object_name)
      } else {
        path
      }
    } else {
      file.path(get_slideimp_path(), full_object_name)
    }
    # read file with fst
    tryCatch(
      {
        obj <- fst::read_fst(file_path, ...)
      },
      error = function(e) {
        stop(
          sprintf(
            paste(
              "Failed to read '%s'.",
              "Did you download '%s' and passed the path or loaded object to this function?",
              "See function `download_slideimp` to download or re-download the required data.",
              "Function failed: %s",
              sep = "\n"
            ),
            full_object_name,
            full_object_name,
            e
          )
        )
      }
    )

    # check sum
    ## ensure that the object loaded with this function is intended.
    ## generated by data-raw/SystemsAge_data.R or similar scripts
    if ((rlang::hash(obj) != force(object_hash)) && object_hash != "skip") {
      stop(
        sprintf(
          "Data integrity check failed. Try re-downloading the '%s.fst' file.",
          force(object_name)
        )
      )
    }
    return(obj)
  }
}
